apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnetjenkinsgithub291024
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnetjenkinsgithub291024 
  name: dotnetjenkinsgithub291024
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnetjenkinsgithub291024
    weight: 100 
